import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
    throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Create Supabase client with service role key for backend operations
export const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: {
        autoRefreshToken: false,
        persistSession: false
    }
});

// Database types (will be generated by Supabase)
export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string;
                    email: string;
                    name: string;
                    phone: string;
                    role: 'CUSTOMER' | 'RIDER' | 'HUB_MANAGER' | 'ADMIN';
                    status: 'ACTIVE' | 'INACTIVE';
                    avatar_url: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>;
                Update: Partial<Database['public']['Tables']['users']['Insert']>;
            };
            shipments: {
                Row: {
                    id: string;
                    tracking_id: string;
                    customer_id: string;
                    rider_id: string | null;
                    recipient_name: string;
                    pickup_address: {
                        street: string;
                        city: string;
                        state: string;
                        zipCode: string;
                    };
                    dropoff_address: {
                        street: string;
                        city: string;
                        state: string;
                        zipCode: string;
                    };
                    weight: number;
                    description: string;
                    service_type: 'STANDARD' | 'EXPRESS' | 'SAME_DAY';
                    status: 'PENDING' | 'APPROVED' | 'PICKED_UP' | 'IN_TRANSIT' | 'DELIVERED' | 'CANCELLED';
                    payment_method: 'CREDIT_CARD' | 'WALLET' | 'COD';
                    payment_status: 'PENDING' | 'PAID' | 'FAILED';
                    price: number;
                    distance_miles: number | null;
                    estimated_delivery: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['shipments']['Row'], 'id' | 'tracking_id' | 'created_at' | 'updated_at'>;
                Update: Partial<Database['public']['Tables']['shipments']['Insert']>;
            };
            addresses: {
                Row: {
                    id: string;
                    address_string: string;
                    street: string;
                    city: string;
                    state: string;
                    zip_code: string;
                    latitude: number;
                    longitude: number;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['addresses']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['addresses']['Insert']>;
            };
        };
    };
}
